### ISSUE TITLE
Enable/Disable Notifications Button Added Doesn't Work

### ISSUE THREAD

**Issue by UInt2048** [Greg0109/quiet#1]
It successfully changes state, but the notifications count remains.

I'm on iOS 14.1 with an iPhone 12, but another commenter 4 months ago [here](https://www.idownloadblog.com/2020/12/18/quiet/) also was experiencing problems on a Xs on 13.5.

**Comment by Greg0109** [comment]
Thats the way it’s supposed to work. It doesn’t disable the notification badges only the bulletin
